package main

import (
	"os"
	"path/filepath"
	"slices"
	"testing"

	ev "github.com/hallow-inc/claude-plugins/plugins/hallow-assurance/internal/evidence"
)

const fuzzTargetSrc = "package a\n\nimport \"testing\"\n\nfunc FuzzParse(f *testing.F) {\n\tf.Add(\"x\")\n\tf.Add(\"yy\")\n\tf.Fuzz(func(t *testing.T, s string) {\n\t\tif s == \"bad\" {\n\t\t\tt.Fatal(\"bad\")\n\t\t}\n\t\t_ = Parse(s)\n\t})\n}\n"

const parseSrc = "package a\n\nfunc Parse(s string) int { return len(s) }\n"

func fuzzJUnit(t *testing.T, dir string) ev.JUnit {
	t.Helper()
	out := t.TempDir()
	resp, stderr, code := runIn(t, dir, "run", "VER-ROBUST-FUZZ", "--changed-from", "HEAD", "--out", out)
	if code != 0 {
		t.Fatalf("run failed %d: %s", code, stderr)
	}
	data, err := os.ReadFile(filepath.Join(out, resp.Evidence[0].Path))
	if err != nil {
		t.Fatal(err)
	}
	j, err := ev.ParseJUnit(data)
	if err != nil {
		t.Fatalf("%v\n%s", err, data)
	}
	return j
}

func sourceProps(s ev.Suite) []string {
	var out []string
	for _, p := range s.Properties {
		if p.Name == "assure.source" {
			out = append(out, p.Value)
		}
	}
	return out
}

func TestFuzzRunsSeedsOnlyAndAttributesChangedSources(t *testing.T) {
	dir := committedModule(t, map[string]string{
		"a/a.go":                          parseSrc,
		"a/gen.go":                        "// Code generated by x. DO NOT EDIT.\n\npackage a\n\nvar G = 1\n",
		"a/a_test.go":                     fuzzTargetSrc,
		"a/testdata/fuzz/FuzzParse/seed1": "go test fuzz v1\nstring(\"ok\")\n",
		"b/b.go":                          "package b\n\nfunc B() int { return 1 }\n",
		"b/b_test.go":                     "package b\n\nimport \"testing\"\n\nfunc TestB(t *testing.T) { _ = B() }\n",
	})
	writeFiles(t, dir, map[string]string{
		"a/a.go":      "package a\n\nfunc Parse(s string) int { return len(s) + 0 }\n",
		"a/gen.go":    "// Code generated by x. DO NOT EDIT.\n\npackage a\n\nvar G = 2\n",
		"a/a_test.go": fuzzTargetSrc + "\n// touched\n",
		"b/b.go":      "package b\n\nfunc B() int { return 2 }\n",
		"b/b_test.go": "package b\n\nimport \"testing\"\n\nfunc TestB(t *testing.T) { _ = B() + 1 }\n",
	})
	before := gitState(t, dir)
	j := fuzzJUnit(t, dir)
	if after := gitState(t, dir); after != before {
		t.Fatalf("repository changed:\nbefore %s\nafter %s", before, after)
	}
	if n, _ := filepath.Glob(filepath.Join(dir, "a/testdata/fuzz/FuzzParse/*")); len(n) != 1 {
		t.Fatalf("corpus files %v; seeds run, fuzzing must not add inputs", n)
	}
	if len(j.Suites) != 2 {
		t.Fatalf("suites %+v, want one per package with a changed source", j.Suites)
	}
	a, b := j.Suites[0], j.Suites[1]
	if len(a.Cases) != 1 || a.Cases[0].Name != "a.FuzzParse" || a.Cases[0].Outcome != ev.Passed {
		t.Fatalf("suite a cases %+v; one passing FuzzParse case expected", a.Cases)
	}
	if got := sourceProps(a); !slices.Equal(got, []string{"a/a.go"}) {
		t.Fatalf("suite a sources %v; tests and generated files are not sources", got)
	}
	if len(b.Cases) != 0 || !slices.Equal(sourceProps(b), []string{"b/b.go"}) {
		t.Fatalf("suite b %+v; a package without Fuzz targets is a suite with properties and no cases", b)
	}
}

func TestFuzzCommittedCorpusFailureIsFailedCase(t *testing.T) {
	dir := committedModule(t, map[string]string{
		"a/a.go":                          parseSrc,
		"a/a_test.go":                     fuzzTargetSrc,
		"a/testdata/fuzz/FuzzParse/crash": "go test fuzz v1\nstring(\"bad\")\n",
	})
	writeFiles(t, dir, map[string]string{"a/a.go": "package a\n\nfunc Parse(s string) int { return len(s) + 0 }\n"})
	j := fuzzJUnit(t, dir)
	if j.Failures != 1 || len(j.Suites) != 1 || len(j.Suites[0].Cases) != 1 || j.Suites[0].Cases[0].Outcome != ev.Failed {
		t.Fatalf("got %+v; the corpus input makes FuzzParse fail", j)
	}
}
