package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"pgregory.net/rapid"

	"github.com/hallow-inc/claude-plugins/plugins/hallow-assurance/schemas"
)

func invoke(t interface{ Fatalf(string, ...any) }, args ...string) (map[string]any, []byte) {
	var out, errb bytes.Buffer
	if code := run(args, &out, &errb); code != 0 {
		t.Fatalf("%v exited %d: %s", args, code, errb.String())
	}
	var v map[string]any
	if err := json.Unmarshal(out.Bytes(), &v); err != nil {
		t.Fatalf("%v: %v", args, err)
	}
	return v, out.Bytes()
}

func roles(v map[string]any) map[string]string {
	out := map[string]string{}
	for _, f := range v["files"].([]any) {
		m := f.(map[string]any)
		out[m["path"].(string)] = m["role"].(string)
	}
	return out
}

func TestDescribeConformsToProtocol(t *testing.T) {
	v, raw := invoke(t, "describe")
	vs, err := schemas.Validate(schemas.AdapterDescribe, raw)
	if err != nil || len(vs) > 0 {
		t.Fatalf("describe invalid: %v %v", err, vs)
	}
	if c := v["claims"].([]any); len(c) != 1 || c[0] != "**/*.go" {
		t.Fatalf("claims = %v", c)
	}
	var fast, slow []string
	for id, o := range v["objectives"].(map[string]any) {
		if _, ok := runners[id]; !ok {
			t.Errorf("describe lists %s but run has no runner for it", id)
		}
		if o.(map[string]any)["fast"] == true {
			fast = append(fast, id)
		} else {
			slow = append(slow, id)
		}
	}
	slices.Sort(fast)
	slices.Sort(slow)
	if !slices.Equal(fast, []string{"CODE-ZERO-WARNINGS", "VER-TEST-BUDGET", "VER-TESTS-PASS"}) ||
		!slices.Equal(slow, []string{"CODE-CHECK-RETURNS", "CODE-COMPLEXITY", "CODE-NO-UNSAFE", "CODE-RESOURCE-BOUNDS", "VER-COVERAGE-RESOLUTION", "VER-FAIL-ON-BASE", "VER-MUTATION-CHANGED", "VER-ROBUST-FUZZ"}) {
		t.Fatalf("fast %v, slow %v; only cheap objectives may run on the Stop path (per-turn latency budget)", fast, slow)
	}
}

var segGen = rapid.StringMatching(`[a-z]{1,6}`)

func TestTestSuffixAlwaysClassifiesAsTest(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		dirs := rapid.SliceOfN(segGen.Filter(func(s string) bool { return s != "testdata" }), 0, 3).Draw(t, "dirs")
		p := strings.Join(append(dirs, segGen.Draw(t, "name")+"_test.go"), "/")
		v, raw := invoke(t, "classify", p)
		if vs, err := schemas.Validate(schemas.AdapterClassify, raw); err != nil || len(vs) > 0 {
			t.Fatalf("classify invalid: %v %v", err, vs)
		}
		if got := roles(v)[p]; got != "test" {
			t.Fatalf("%s: role %q", p, got)
		}
	})
}

func TestNonGoFilesOutsideConfigAreOmitted(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		dirs := rapid.SliceOfN(segGen.Filter(func(s string) bool { return s != "testdata" }), 0, 3).Draw(t, "dirs")
		name := segGen.Draw(t, "name") + rapid.SampledFrom([]string{".md", ".json", ".ts", ".gox", ""}).Draw(t, "ext")
		p := strings.Join(append(dirs, name), "/")
		if v, _ := invoke(t, "classify", p); len(v["files"].([]any)) != 0 {
			t.Fatalf("%s was claimed: %v", p, v["files"])
		}
	})
}

func TestGeneratedHeader(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	files := map[string]string{
		"types.go":    "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n",
		"late.go":     "package api\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\n",
		"almost.go":   "// Code generated by hand, edit freely.\npackage api\n",
		"gen_test.go": "// Code generated by mockgen. DO NOT EDIT.\npackage api\n",
	}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	v, _ := invoke(t, "classify", "types.go", "late.go", "almost.go", "gen_test.go", "missing.go", "README.md", "go.mod", "a/testdata/fuzz/FuzzX/seed")
	want := map[string]string{
		"types.go": "generated", "late.go": "source", "almost.go": "source", "gen_test.go": "generated",
		"missing.go": "source", "go.mod": "config", "a/testdata/fuzz/FuzzX/seed": "fuzz_corpus",
	}
	got := roles(v)
	for p, r := range want {
		if got[p] != r {
			t.Errorf("%s: role %q, want %q", p, got[p], r)
		}
	}
	if _, ok := got["README.md"]; ok {
		t.Error("README.md was claimed")
	}
	var order []string
	for _, f := range v["files"].([]any) {
		order = append(order, f.(map[string]any)["path"].(string))
	}
	if strings.Join(order, ",") != "types.go,late.go,almost.go,gen_test.go,missing.go,go.mod,a/testdata/fuzz/FuzzX/seed" {
		t.Errorf("output not in input order: %v", order)
	}
}

func TestErrors(t *testing.T) {
	var out, errb bytes.Buffer
	if run([]string{"frobnicate"}, &out, &errb) == 0 {
		t.Error("unknown subcommand exited 0")
	}
	dir := t.TempDir()
	t.Chdir(dir)
	if err := os.WriteFile("locked.go", []byte("package x\n"), 0o000); err != nil {
		t.Fatal(err)
	}
	if os.Getuid() != 0 && run([]string{"classify", "locked.go"}, &out, &errb) == 0 {
		t.Error("unreadable claimed file exited 0")
	}
}
